---
plugin: aws_ec2
regions:
  - eu-west-2
  - us-east-1
  - us-west-2

keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type
  - key: placement.region
    prefix: aws_region
  - key: state.name
    prefix: instance_state

filters:
  - tag:Project: AWS Security Automation

compose:
  ansible_host: public_ip_address | default(private_ip_address)
  ansible_user: ec2-user
  ec2_state: state.name
  ec2_arch: architecture
  ec2_instance_id: instance_id
  ec2_placement: placement.availability_zone

groups:
  # Group by instance state
  running: ec2_state == "running"
  stopped: ec2_state == "stopped"

  # Group by environment
  development: tag_Environment == "dev"
  staging: tag_Environment == "staging"
  production: tag_Environment == "prod"

  # Group by role
  security_automation: tag_Role == "security-automation"
  monitoring: tag_Role == "monitoring"
  database: tag_Role == "database"

  # Group by OS
  amazon_linux: platform is defined and "amazon" in platform
  ubuntu: platform is defined and "ubuntu" in platform

hostnames:
  - tag:Name
  - instance-id
  - private-ip-address