---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: restart cloudwatch-agent
  systemd:
    name: amazon-cloudwatch-agent
    state: restarted

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted