---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart security-automation
  systemd:
    name: security-automation
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted