---
# Security hardening verification tasks
- name: Check SSH configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  check_mode: yes
  register: ssh_config_check
  failed_when: ssh_config_check.changed
  loop:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
  tags: [verification, ssh]

- name: Verify firewall is active
  command: "{{ 'ufw status' if ansible_os_family == 'Debian' else 'firewall-cmd --state' }}"
  register: firewall_status
  failed_when:
    - (ansible_os_family == "Debian" and "active" not in firewall_status.stdout)
    - (ansible_os_family == "RedHat" and "running" not in firewall_status.stdout)
  tags: [verification, firewall]

- name: Check fail2ban is running
  service_facts:
  failed_when: "'fail2ban' not in services or services['fail2ban'].state != 'running'"
  tags: [verification, fail2ban]

- name: Verify audit daemon is active
  service_facts:
  failed_when: "'auditd' not in services or services['auditd'].state != 'running'"
  tags: [verification, audit]

- name: Check kernel security parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  check_mode: yes
  register: sysctl_check
  failed_when: sysctl_check.changed
  loop:
    - { name: net.ipv4.ip_forward, value: 0 }
    - { name: net.ipv4.conf.all.send_redirects, value: 0 }
    - { name: kernel.randomize_va_space, value: 2 }
  tags: [verification, kernel]

- name: Verify security tools are installed
  package_facts:
    manager: auto
  failed_when: item not in ansible_facts.packages
  loop:
    - aide
    - rkhunter
    - clamav
  tags: [verification, tools]

- name: Check file permissions on critical files
  stat:
    path: "{{ item.path }}"
  register: file_perms
  failed_when: file_perms.stat.mode != item.mode
  loop:
    - { path: '/etc/ssh/sshd_config', mode: '0600' }
    - { path: '/etc/passwd', mode: '0644' }
    - { path: '/etc/shadow', mode: '0640' }
  tags: [verification, permissions]

- name: Display hardening verification results
  debug:
    msg: |
      Security hardening verification completed successfully:
      ✓ SSH hardening verified
      ✓ Firewall is active
      ✓ Fail2ban is running
      ✓ Audit daemon is active
      ✓ Kernel security parameters configured
      ✓ Security tools installed
      ✓ File permissions correct